# Generated by Django 5.1.7 on 2025-04-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255, null=True)),
                ('coursefee', models.IntegerField(null=True)),
            ],
        ),
    ]
