# Generated by Django 5.1.7 on 2025-04-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkeyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_address', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foreignkeyapp.course')),
            ],
        ),
    ]
